
# Generated by manim_helper at 24-09-17_19-22-04

from manim import *

import manim_helper

class Show(Scene):

    def prepare(self) -> None:
        loader = manim_helper.TextLoader("script_parsing.json")
        text_data = loader.load()
        self.objects = loader.apply(text_data)
        self.director = manim_helper.Director(self.objects, "action_parsing.json")

    def construct(self) -> None:
        self.prepare()
        self.director.set_target_show(self)
        self.director.load_actions()
        self.director.start_play()   
